[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/sshd.err.log
stdout_logfile=/var/log/supervisor/sshd.out.log

[program:nfsplugin]
command=/bin/bash -c "/nfsplugin $SUPERVISOR_CUSTOM_ARGS"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nfsplugin.err.log
stdout_logfile=/var/log/supervisor/nfsplugin.out.log
